#!/bin/bash
if [ $# -ne 3 ]
then
	echo -e "Ussage:\n bash ./query3 -Daddresses='serverAddresses' -DinPath=inputDirectory -DoutPath=outputDirectory";
else
    java -DqueryNumber=3 $1 $2 $3 -cp 'lib/jars/*' "ar.edu.itba.pod.client.Client"
fi
